# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Find Sequence in Integer Vector
#'
#' @param vec
#' An integer vecotr
#' @param seq
#' The sequence
#'
#' @useDynLib tpfuns, .registration = TRUE
#' @importFrom Rcpp sourceCpp
#'
#' @export
SeqInVec <- function(myVector, mySequence) {
    .Call(`_tpfuns_SeqInVec`, myVector, mySequence)
}

#' Find Sequence in Integer Vector
#'
#' @param vec
#' An integer vecotr
#' @param seq
#' The sequence
#'
#' @useDynLib tpfuns, .registration = TRUE
#' @importFrom Rcpp sourceCpp
#'
#' @export
SeqInVecOpt <- function(myVector, mySequence) {
    .Call(`_tpfuns_SeqInVecOpt`, myVector, mySequence)
}

